id: P008068
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12985
  title: ལྕེ་བཙུན་ཆེན་པོ་བི་མ་ལའི་ཟབ་ཏིག་གཏེར་གཞུང་དང་ཡན་ལག་གི་ཆོས་སྡེའི་སྐོར།
  author: ''
  volumes:
    c11b09add6a24bc6894592c1cb2a0dd5:
      image_group_id: I1KG13062
      title: ''
      volume_number: 1
      total_pages: 412
ebook_metadata:
  title: ལྕེ་བཙུན་ཆེན་པོ་བི་མ་ལའི་ཟབ་ཏིག་གཏེར་གཞུང་དང་ཡན་ལག་གི་ཆོས་སྡེའི་སྐོར།
  author: ''
  sku: P008068
  cover: cover.jpg
  layers:
  - pagination
