id: P008068
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12985
  title: ལྕེ་བཙུན་ཆེན་པོ་བི་མ་ལའི་ཟབ་ཏིག་གཏེར་གཞུང་དང་ཡན་ལག་གི་ཆོས་སྡེའི་སྐོར།
  author: ''
  volumes:
    5bccdd64faa04f3ab67ac9f276f95ba7:
      image_group_id: I1KG13062
      title: Volume 1 of lce btsun chen po bi ma la'i zab tig gter gzhung dang yan
        lag gi chos sde'i skor/
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
