id: IB8438BD8
legacy_id: P008068
ocr_import_info:
  bdrc_scan_id: W1KG12985
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:01:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T02:29:03.128506+00:00'
last_modified: 2022-08-27 10:29:39.398380
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12985
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12985
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྕེ་བཙུན་ཆེན་པོ་བི་མ་ལའི་ཟབ་ཏིག་གཏེར་གཞུང་དང་ཡན་ལག་གི་ཆོས་སྡེའི་སྐོར།
  author: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9434631873402574
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG13062:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13062
      total_pages: 412
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13062.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9434631873402574
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
